# Studying the probabilities of Hoo Hey How (魚蝦蟹) 
Hoo Hey How is a Chinese dice-game. Here we just focus on a simplified version of the game: there are 3 dies and each player can put their bet(s) on 1-6. Consider player1 only places one bet every time; player2 bets on two different numbers every time. Return is 1-1.

### Here you can run the cells and see the different outcomes

In [112]:
# Input: choices (list), dice (list)
# Output: total gain (int), at least one correct (1 or 0)
# Function: Given the Fish/Shrimp/Crab choices, and the results of the 3 dies, 
# find the total gain and whether at least one choice was matched 
gain =function(choices, dice){

    total_gain = 0
    at_least_one = FALSE 
    for(choice in choices){
        if(choice %in% dice){
            total_gain = total_gain + sum(dice==choice)
            at_least_one = TRUE
        }
        else{
            total_gain = total_gain - 1
        }
    }
    count = ifelse(at_least_one,1,0)
    return(c(total_gain, count))
}

In [107]:
dice <- floor(runif(3,min=1,max=7))
player1 <- floor(runif(1,min=1,max=7))
gain = gain(player1,dice)
print("The dies are: ")
dice
print("The choice is: ")
player1
print("Player1 gained")
gain[1]

[1] "The dies are: "


[1] 2 5 1

[1] "The choice is: "


[1] 1

[1] "Player1 gained"


[1] 1

In [115]:
dice <- floor(runif(3,min=1,max=7))
player2 <- sample(1:6,2,replace=F)
gain = gain(player2,dice)
print("The dies are: ")
dice
print("The choice is: ")
player2
print("Player2 gained")
gain[1]

[1] "The dies are: "


[1] 6 4 2

[1] "The choice is: "


[1] 4 2

[1] "Player2 gained"


[1] 2

### In a long run, which player would win/lose more?
When we play the game, it feels like we always lose when we bet on one every time; most of the time 0 gain and sometimes gain/lose 2 dollars when we bet on two. It seems betting on two is a better strategy.

Here we run the game similation on 1000000 times and see what's the result:

In [113]:
# Player1
total_score = 0
at_least_one_match_count = 0
for (i in c(1:1000000)){
  dice <- floor(runif(3,min=1,max=7))
  player1 <- floor(runif(1,min=1,max=7))
  score = gain(player1,dice)
  total_score = total_score + score[1]
  at_least_one_match_count = at_least_one_match_count + score[2]
}
average_score = total_score / 1000000.0
print("Player1 gains on average: ")
average_score
print("Prob of Player1 getting at least 1 correct")
prob_at_least_one = at_least_one_match_count / 1000000.0
prob_at_least_one

[1] "Player1 gains on average: "


[1] -0.080198

[1] "Prob of Player1 getting at least 1 correct"


[1] 0.42062

In [114]:
# Player2
total_score = 0
at_least_one_match_count = 0
for (i in c(1:1000000)){
  dice <- floor(runif(3,min=1,max=7))
  player2 <- sample(1:6,2,replace=F)
  score = gain(player2,dice)
  total_score = total_score + score[1]
  at_least_one_match_count = at_least_one_match_count + score[2]
}
average_score = total_score / 1000000.0
print("Player2 gains on average: ")
average_score
prob_at_least_one = at_least_one_match_count / 1000000.0
print("Prob of Player2 getting at least 1 correct")
prob_at_least_one

[1] "Player2 gains on average: "


[1] -0.156995

[1] "Prob of Player2 getting at least 1 correct"


[1] 0.703788

The result tells us the average loss is smaller when we bet on one. But why do we feel the other way?

In fact, when we bet on one number each time, the probability of getting at least one correct is $1-\frac{5}{6} * \frac{5}{6} * \frac{5}{6} = 0.421$, which is smaller than 0.5 so more than half the time you think you have lost.

When we bet on two different numbers each time, the probability of getting at least one correct is $1-\frac{4}{6} * \frac{4}{6} * \frac{4}{6} = 0.704$, which is greater than 0.5 so more than half the time you think you didn't lose.

### Calculating the probabilites and expected values
#### Player1: betting on only one number each time
Prob(gaining 1 dollar) =  $ \frac{1}{6} * \frac{5}{6} * \frac{5}{6} * 3 $  = 0.3472

Prob(gaining 2 dollars) =  $ \frac{1}{6} * \frac{1}{6} * \frac{5}{6} * 3 $  = 0.06944

Prob(gaining 3 dollars) =  $ \frac{1}{6} * \frac{1}{6} * \frac{1}{6} $  = 0.0046296

Expected value = $(-1)*(1-0.421) + 1*0.3472 + 2*0.06944 + 3*0.0046296 = -0.07873$

#### Player2: betting on two different numbers each time
Prob(gaining 0 dollar) =  $ \frac{1}{6} * \frac{4}{6} * \frac{4}{6} * 6 $  = 0.444

Prob(gaining 1 dollar) =  $ \frac{1}{6} * \frac{1}{6} * \frac{4}{6} * 6 $  = 0.111

Prob(gaining 2 dollars) =  $ \frac{1}{6} * \frac{1}{6} * \frac{4}{6} * 6 + \frac{1}{6} * \frac{1}{6} * \frac{1}{6} * 2 $  = 0.120

Prob(gaining 3 dollars) =  $ \frac{1}{6} * \frac{1}{6} * \frac{1}{6} * 6 $  = 0.027778

Expected value = $(-2)*(1-0.704) + 0*0.4444 + 1*0.1111 + 2*0.120 + 3*0.027778 = -0.1584$